services:
  biss_app:
    image: valkyliao/biss-case-law-explorer:latest
    container_name: biss-app
    restart: always
    ports:
      - "15000:5000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
